from tkinter import *
root = Tk()
Letter = BooleanVar()
Numbers= BooleanVar()
Caps= BooleanVar()
Special_Characters= BooleanVar()
Easy_to_Read= BooleanVar()
Easy_to_Memorize= BooleanVar()

cbLetters = Checkbutton(text="Letters", variable=Letter,onvalue = True, offvalue = False, height = 2,width = 15)
cbNumbers = Checkbutton(text="Numbers", variable=Numbers,onvalue = True, offvalue = False, height = 2,width = 15)
cbCaps = Checkbutton(text="Caps", variable=Caps,onvalue = True, offvalue = False, height = 2,width = 15)
cbSpecial = Checkbutton(text="Special Characters", variable=Special_Characters,onvalue = True, offvalue = False, height = 2,width = 15)
cbEasyR = Checkbutton(text="Easy to Read", variable=Easy_to_Read,onvalue = True, offvalue = False, height = 2,width = 15)
cbEasyM = Checkbutton(text="Easy to Memorize", variable=Easy_to_Memorize,onvalue = True, offvalue = False, height = 2,width = 15)
lbTitle = Label(text = "Random Password Generator")
lbPassword = Entry(text = "Pleas Enter Password")
btnGo = Button(text = "Go !")
lbTitle.grid(row = 0,column = 0)
lbPassword.grid(row = 1, column = 0)
btnGo.grid(row = 1, column = 1)
cbSpecial.grid(row = 2,column = 0)
cbCaps.grid(row = 3, column = 0)
cbNumbers.grid(row = 4, column = 0)
cbLetters.grid(row = 5, column = 0)
cbEasyR.grid(row = 6, column = 0)
cbEasyM.grid(row = 7, column = 0)
cbSpecial.grid(row = 8, column = 0)



root.mainloop()
